### ISSUE TITLE
Definitable Named UUID Proposal

### ISSUE THREAD

**Issue by septs** [openble-org/openble-sdk#2]
## Motivation

I think this specification need provide definitable named uuid feature.

Improve code human readability

## Example Code

```yaml
services:
   camera_information:
     // ...
     characteristics:
        // ...
        firmware_revision_string:
           // ...
definitions:
   service-uuids:
      camera_information: 9A5ED1C5-74CC-4C50-B5B6-66A48E7CCFF1
   characteristic-uuids:
      firmware_revision_string: B4EB8905-7411-40A6-A367-2834C2157EA7
```
